// vue3/src/views/components/form/Form.vue
<script setup lang="ts">
import {computed} from 'vue';

import {useRoute, useRouter} from 'vue-router';
import {ModelType, get_form_by_model, type inputFilters} from '@/common/types';
import FormChild from '@/views/components/form/FormChild.vue';

import {useGeneralStore} from '@/common/stores/general';
import {create_form_fields} from '@/common/utils/transformation/form';

import {array_obj_to_obj_with_key} from '@/common/utils/transformation';
import {useAuthStore} from '@/common/stores/auth';

const router = useRouter();
const store = useGeneralStore();

const route = useRoute();

const store_general = useGeneralStore();
const auth_store = useAuthStore();

const url = computed<string>(() => route.params.url as string);
const model = computed<ModelType>(() => route.params.model as ModelType);
const is_add: boolean = url.value === 'add';
const obj = is_add ? {} : array_obj_to_obj_with_key(store.list[model.value] as [], +url.value, 'id');

const controls = computed<inputFilters>(() =>
    create_form_fields(
        get_form_by_model(model.value),
        obj
    )
);

const create_update = async (data: inputFilters) => {
  try {
    await store_general.create_update_row_input_form(data, model.value, url.value, is_add);
    if (model.value === ModelType.teacher) await router.push('/login');
    else if (model.value === ModelType.student && is_add) await router.push(`/${ModelType.student}`);
    else await router.push(`/${ModelType.student}/view/${auth_store.student_id}`);
  } catch (e) {
  }
};
</script>
<template>
  <v-row>
    <v-col class="d-flex flex-row mt-2 justify-space-around" cols="12" sm="12">
      <FormChild :is_add="url === 'add'" :type="model" :controls="controls" @sendForm="create_update"/>
    </v-col>
  </v-row>
</template>

// react/src/views/form/Form.tsx
import { useNavigate, useParams } from 'react-router-dom';
import FormChild from './FormChild';
import { DefaultRootStateProps, ModelType } from '../../types';
import { FormField, get_form_by_model } from '../../types/form';
import { useDispatch, useSelector } from 'react-redux';
import React from 'react';
import { array_obj_to_obj_with_key, create_form_fields } from '../../utils/transformation';
import { createOrUpdateRow } from 'store/modelSlice';
import { AppDispatch } from 'store';

const Form = () => {
    const dispatch = useDispatch<AppDispatch>();
    const navigate = useNavigate();
    const { id, model } = useParams() as {
        id: string;
        model: ModelType;
    };
    const { list, student_id, user_id } = useSelector((state: DefaultRootStateProps) => state.models);

    const model_objs = list[model];
    const is_add: boolean = id === 'add';

    const obj = is_add ? {} : array_obj_to_obj_with_key(model_objs, id, 'id') ?? {};
    const fields: FormField[] = create_form_fields(get_form_by_model(model), obj);

    const handleSubmit = async (send_fields: FormField[]) => {
        const data = Object.fromEntries(send_fields.map((f) => [f.key, f.value]));
        if (model.includes(ModelType.student)) data.teacher_id = user_id;
        if (model.includes(ModelType.assignment)) {
            data.teacher_id = user_id;
            data.student_id = student_id;
        }
        try {
            await dispatch(createOrUpdateRow({ model, data, id })).unwrap();
            if (model === ModelType.teacher) navigate(`/login`);
            else if (model === ModelType.student && is_add) navigate(`/${ModelType.student}`);
            else navigate(`/view/${student_id}`);
        } catch (err) {
            console.error('Error submitting form:', err);
        }
    };

    return <FormChild title={is_add ? `Add ${model}` : `Edit ${model}`} fields={fields} onSubmit={handleSubmit} />;
};

export default Form;
